services:
  - type: web
    name: regenardhi
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9  # Changed from 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      # Railway MySQL credentials - add manually in Render dashboard
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DB
        sync: false
      - key: MYSQL_PORT
        value: 3306
